package com.jalalsoft.shapes.application;

import com.jalalsoft.shapes.command.CommandFactory;
import com.jalalsoft.shapes.io.CommandInputStream;
import com.jalalsoft.shapes.io.CommandOutputStream;

import java.io.IOException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws IOException {

        new REPLService(CommandFactory.init()).takeCommands(new CommandInputStream(System.in), new CommandOutputStream(System.out));


    }
}
